name: Build static site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          npm install -f
          npm run build
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "Build static site"
